import {
    accessibilityIcon,
    angularIcon,
    arrowDownIcon,
    arrowLeftIcon,
    arrowRightIcon,
    arrowUpIcon,
    awsIcon,
    blueskyIcon,
    claudeIcon,
    closeIcon,
    cSharpIcon,
    cssIcon,
    dockerIcon,
    dotNetIcon,
    downloadIcon,
    externalLinkIcon,
    gitHubCopilotIcon,
    gitHubIcon,
    gitIcon,
    graduationCapIcon,
    htmlIcon,
    Icon,
    javaScriptIcon,
    linkedInIcon,
    mailIcon,
    menuIcon,
    moonIcon,
    nodeJsIcon,
    playwrightIcon,
    reactIcon,
    sunIcon,
    typeScriptIcon,
} from '@naovixen/components';

import type { IShowcase } from '../../interfaces/IShowcase';

const iconsByName = {
    accessibilityIcon,
    angularIcon,
    arrowDownIcon,
    arrowLeftIcon,
    arrowRightIcon,
    arrowUpIcon,
    awsIcon,
    blueskyIcon,
    claudeIcon,
    closeIcon,
    cSharpIcon,
    cssIcon,
    dockerIcon,
    dotNetIcon,
    downloadIcon,
    externalLinkIcon,
    gitHubCopilotIcon,
    gitHubIcon,
    gitIcon,
    graduationCapIcon,
    htmlIcon,
    javaScriptIcon,
    linkedInIcon,
    mailIcon,
    menuIcon,
    moonIcon,
    nodeJsIcon,
    playwrightIcon,
    reactIcon,
    sunIcon,
    typeScriptIcon,
};

export const iconShowcase: IShowcase = {
    name: 'Icon',
    examples: Object.entries(iconsByName).map(([name, source]) => ({
        name,
        render: () => <Icon source={source} />,
    })),
};
